// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7QO4V5HghL78OYv-r5JwXhf-x_jdBT4M',
    appId: '1:823570857451:web:c86b66964d48159ebd6dae',
    messagingSenderId: '823570857451',
    projectId: 'shoppy-13d7b',
    authDomain: 'shoppy-13d7b.firebaseapp.com',
    storageBucket: 'shoppy-13d7b.appspot.com',
    measurementId: 'G-7HZHYNRT7T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2NMtfOFjaSRoab4MtA9oDGFJ3ZSXK-Kg',
    appId: '1:823570857451:android:a50dbb33e7cc901ebd6dae',
    messagingSenderId: '823570857451',
    projectId: 'shoppy-13d7b',
    storageBucket: 'shoppy-13d7b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBS697K8Dmh97pbDM1nCblqkU9tVsoNmnE',
    appId: '1:823570857451:ios:f4b7a363b40d758ebd6dae',
    messagingSenderId: '823570857451',
    projectId: 'shoppy-13d7b',
    storageBucket: 'shoppy-13d7b.appspot.com',
    iosClientId: '823570857451-tiu3p50nfl4bcolit4scgpf843t2qi0i.apps.googleusercontent.com',
    iosBundleId: 'com.example.sidebar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBS697K8Dmh97pbDM1nCblqkU9tVsoNmnE',
    appId: '1:823570857451:ios:f4b7a363b40d758ebd6dae',
    messagingSenderId: '823570857451',
    projectId: 'shoppy-13d7b',
    storageBucket: 'shoppy-13d7b.appspot.com',
    iosClientId: '823570857451-tiu3p50nfl4bcolit4scgpf843t2qi0i.apps.googleusercontent.com',
    iosBundleId: 'com.example.sidebar',
  );
}
